import PropTypes from "prop-types";
import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function LogIn({ setLoggedIn }) {
  const logIn = () => {
    setLoggedIn(true);
  };

  return (
    <>
      <Head>
        <title>Log in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <button type="button" onClick={logIn}>
            <p>login!</p>
          </button>
        </div>
      </main>
    </>
  );
}

LogIn.propTypes = {
  // loggedIn: PropTypes.bool.isRequired,
  setLoggedIn: PropTypes.func.isRequired,
};
